import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`pages_blocks_faq_block\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_home_section_about\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_home_section_logo_cloud\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_home_section_process\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_home_section_projects\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_home_section_services\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`hst\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_home_section_cta\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_checklist_grid\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_portfolio_listing\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_blog_listing\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_latest_posts\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_latest_portfolios\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_faq_block\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_home_section_about\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_home_section_logo_cloud\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_home_section_process\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_home_section_projects\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_home_section_services\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`_hst_v\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_home_section_cta\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_checklist_grid\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_portfolio_listing\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_blog_listing\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_latest_posts\` ADD \`title_max_width\` text DEFAULT 'none';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_latest_portfolios\` ADD \`title_max_width\` text DEFAULT 'none';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`pages_blocks_faq_block\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_home_section_about\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_home_section_logo_cloud\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_home_section_process\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_home_section_projects\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_home_section_services\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`hst\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_home_section_cta\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_checklist_grid\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_portfolio_listing\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_blog_listing\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_latest_posts\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_latest_portfolios\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_faq_block\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_home_section_about\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_home_section_logo_cloud\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_home_section_process\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_home_section_projects\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_home_section_services\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`_hst_v\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_home_section_cta\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_checklist_grid\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_portfolio_listing\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_blog_listing\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_latest_posts\` DROP COLUMN \`title_max_width\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_latest_portfolios\` DROP COLUMN \`title_max_width\`;`)
}
