/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    portfolios: Portfolio;
    'portfolio-tags': PortfolioTag;
    posts: Post;
    tags: Tag;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    portfolios: PortfoliosSelect<false> | PortfoliosSelect<true>;
    'portfolio-tags': PortfolioTagsSelect<false> | PortfolioTagsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('pt' | 'en') | ('pt' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'pt' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'defaultHero';
    eyebrow?: string | null;
    /**
     * Use *palavra* para laranja. Use \n para quebra de linha.
     */
    heroTitle?: string | null;
    heroDescription?: string | null;
    cta1Label?: string | null;
    cta1Href?: string | null;
    cta2Label?: string | null;
    cta2Href?: string | null;
    heroImage?: (number | null) | Media;
  };
  layout: (
    | FaqBlockBlock
    | SectionAboutBlock
    | SectionLogoCloudBlock
    | SectionProcessBlock
    | SectionProjectsBlock
    | SectionServicesBlock
    | SectionStatsBlock
    | SectionTestimonialsBlock
    | SectionCtaBlock
    | ContactSectionBlock
    | SectionContactBlock
    | ChecklistGridBlock
    | PullQuoteBlock
    | PortfolioListingBlock
    | BlogListingBlock
    | LatestPostsBlock
    | LatestPortfoliosBlock
  )[];
  publishedAt?: string | null;
  /**
   * URL slug da página. Use "home" para a página inicial.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlockBlock".
 */
export interface FaqBlockBlock {
  eyebrow?: string | null;
  /**
   * Use *palavra* para laranja. Use \n para quebra de linha.
   */
  title: string;
  /**
   * Limita a largura do título apenas em telas ≥ 1024px (desktop).
   */
  titleMaxWidth: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  defaultOpenIndex?: number | null;
  items: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionAboutBlock".
 */
export interface SectionAboutBlock {
  eyebrow: string;
  /**
   * Use *palavra* para laranja. Use \n para quebra de linha.
   */
  title: string;
  /**
   * Limita a largura do título apenas em telas ≥ 1024px (desktop).
   */
  titleMaxWidth: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  description: string;
  ctaLabel: string;
  ctaHref: string;
  features: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  image: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeSectionAbout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionLogoCloudBlock".
 */
export interface SectionLogoCloudBlock {
  eyebrow: string;
  /**
   * Use *palavra* para laranja. Use \n para quebra de linha.
   */
  title?: string | null;
  /**
   * Limita a largura do título apenas em telas ≥ 1024px (desktop).
   */
  titleMaxWidth: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  description?: string | null;
  partners: {
    logo: number | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeSectionLogoCloud';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionProcessBlock".
 */
export interface SectionProcessBlock {
  background?: ('dark' | 'white') | null;
  eyebrow: string;
  /**
   * Use *palavra* para laranja. Use \n para quebra de linha.
   */
  title: string;
  /**
   * Limita a largura do título apenas em telas ≥ 1024px (desktop).
   */
  titleMaxWidth: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  description?: string | null;
  /**
   * The step number that will be highlighted in orange (0 = first).
   */
  highlightIndex?: number | null;
  steps: {
    title: string;
    description?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeSectionProcess';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionProjectsBlock".
 */
export interface SectionProjectsBlock {
  eyebrow: string;
  /**
   * Use *palavra* para laranja. Use \n para quebra de linha.
   */
  title: string;
  /**
   * Limita a largura do título apenas em telas ≥ 1024px (desktop).
   */
  titleMaxWidth: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  portfolioLabel?: string | null;
  portfolioHref?: string | null;
  projects: {
    tag: string;
    tagVariant: 'blue' | 'orange';
    accent: 'blue' | 'orange';
    client: string;
    year: string;
    title: string;
    result?: string | null;
    motifType: 'tagMark' | 'dashboard' | 'arrowCurve';
    href?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeSectionProjects';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionServicesBlock".
 */
export interface SectionServicesBlock {
  eyebrow?: string | null;
  /**
   * Use *palavra* para laranja. Use \n para quebra de linha.
   */
  title?: string | null;
  /**
   * Limita a largura do título apenas em telas ≥ 1024px (desktop).
   */
  titleMaxWidth: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  description?: string | null;
  services: {
    name: string;
    variant: 'blue' | 'orange';
    description: string;
    iconType: 'globe' | 'cart' | 'landing' | 'screen' | 'brand' | 'code';
    /**
     * ✓ items that appear below the description.
     */
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeSectionServices';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionStatsBlock".
 */
export interface SectionStatsBlock {
  showDecoration?: boolean | null;
  stats: {
    value: string;
    label: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeSectionStats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionTestimonialsBlock".
 */
export interface SectionTestimonialsBlock {
  eyebrow: string;
  /**
   * Use *palavra* para laranja. Use \n para quebra de linha.
   */
  title: string;
  /**
   * Limita a largura do título apenas em telas ≥ 1024px (desktop).
   */
  titleMaxWidth: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  description?: string | null;
  ratingValue: string;
  reviewCount: string;
  testimonials: {
    quote: string;
    author: string;
    role?: string | null;
    avatarVariant: 'blue' | 'orange';
    surface: 'paper' | 'card';
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeSectionTestimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionCtaBlock".
 */
export interface SectionCtaBlock {
  variant: 'blue' | 'orange' | 'white';
  eyebrow?: string | null;
  /**
   * Use *palavra* para destacar em laranja. Use \n para quebrar linha.
   */
  title: string;
  /**
   * Limita a largura do título apenas em telas ≥ 1024px (desktop).
   */
  titleMaxWidth: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  description?: string | null;
  cta1Label: string;
  cta1Href: string;
  cta1Variant: 'primary' | 'blue' | 'ghost' | 'white';
  cta2Label?: string | null;
  cta2Href?: string | null;
  cta2Variant?: ('primary' | 'blue' | 'ghost' | 'white') | null;
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeSectionCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactSectionBlock".
 */
export interface ContactSectionBlock {
  eyebrow?: string | null;
  heading?: string | null;
  sidebarEyebrow?: string | null;
  successTitle?: string | null;
  successMessage?: string | null;
  channels?:
    | {
        icon: 'email' | 'phone' | 'whatsapp' | 'instagram' | 'linkedin' | 'location';
        label: string;
        value: string;
        hint?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionContactBlock".
 */
export interface SectionContactBlock {
  email: string;
  emailHref: string;
  phone: string;
  phoneHref: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeSectionContact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChecklistGridBlock".
 */
export interface ChecklistGridBlock {
  eyebrow?: string | null;
  /**
   * Use *palavra* para laranja. Use \n para quebra de linha.
   */
  title: string;
  /**
   * Limita a largura do título apenas em telas ≥ 1024px (desktop).
   */
  titleMaxWidth: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  items: {
    title: string;
    description?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'checklistGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock".
 */
export interface PullQuoteBlock {
  eyebrow?: string | null;
  quote: string;
  author?: string | null;
  role?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pullQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioListingBlock".
 */
export interface PortfolioListingBlock {
  eyebrow?: string | null;
  /**
   * Use *palavra* para laranja. Use \n para quebra de linha.
   */
  title?: string | null;
  /**
   * Limita a largura do título apenas em telas ≥ 1024px (desktop).
   */
  titleMaxWidth: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  showFilters?: boolean | null;
  showViewToggle?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'portfolioListing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogListingBlock".
 */
export interface BlogListingBlock {
  /**
   * Appears as a banner above the listing. Leave empty to hide.
   */
  featuredPost?: (number | null) | Post;
  eyebrow?: string | null;
  /**
   * Use *palavra* para laranja. Use \n para quebra de linha.
   */
  title?: string | null;
  /**
   * Limita a largura do título apenas em telas ≥ 1024px (desktop).
   */
  titleMaxWidth: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  postsPerPage?: number | null;
  showSearch?: boolean | null;
  showFilters?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogListing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Short text shown in the posts listing. Recommended maximum: 160 characters.
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  tags?: (number | Tag)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Imagem exibida nos cards de listagem de posts.
   */
  featuredImage?: (number | null) | Media;
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPostsBlock".
 */
export interface LatestPostsBlock {
  eyebrow?: string | null;
  /**
   * Use *palavra* para laranja. Use \n para quebra de linha.
   */
  title?: string | null;
  /**
   * Limita a largura do título apenas em telas ≥ 1024px (desktop).
   */
  titleMaxWidth: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  buttonLabel?: string | null;
  buttonHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'latestPosts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPortfoliosBlock".
 */
export interface LatestPortfoliosBlock {
  eyebrow?: string | null;
  /**
   * Use *palavra* para laranja. Use \n para quebra de linha.
   */
  title?: string | null;
  /**
   * Limita a largura do título apenas em telas ≥ 1024px (desktop).
   */
  titleMaxWidth: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  buttonLabel?: string | null;
  buttonHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'latestPortfolios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolios".
 */
export interface Portfolio {
  id: number;
  title: string;
  client: string;
  /**
   * Aparece abaixo do título na página do case.
   */
  summary?: string | null;
  image: number | Media;
  tag?: (number | null) | PortfolioTag;
  tagVariant?: ('blue' | 'orange') | null;
  accent?: ('blue' | 'orange') | null;
  year?: string | null;
  /**
   * Exibido no card da listagem. Ex: +38% ticket médio
   */
  result?: string | null;
  siteUrl?: string | null;
  /**
   * Botão "Próximo projeto" no hero.
   */
  nextProjectHref?: string | null;
  publishedAt?: string | null;
  sector?: string | null;
  /**
   * Ex: Site, POS, Reservas
   */
  deliverables?: string | null;
  /**
   * Ex: 10 semanas
   */
  duration?: string | null;
  /**
   * Use *palavra* para laranja.
   */
  challengeTitle?: string | null;
  /**
   * Parágrafos separados por linha em branco.
   */
  challengeBody?: string | null;
  processSteps?:
    | {
        /**
         * Ex: 01
         */
        number?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        label?: string | null;
        accent?: ('blue' | 'orange') | null;
        id?: string | null;
      }[]
    | null;
  quoteText?: string | null;
  quoteAuthor?: string | null;
  quoteRole?: string | null;
  stats?:
    | {
        /**
         * Ex: +38%
         */
        value?: string | null;
        /**
         * Ex: Ticket médio após redesign
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  team?:
    | {
        name?: string | null;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  stack?:
    | {
        tool?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedPortfolios?: (number | Portfolio)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-tags".
 */
export interface PortfolioTag {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'portfolios';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'portfolio-tags';
        value: number | PortfolioTag;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        eyebrow?: T;
        heroTitle?: T;
        heroDescription?: T;
        cta1Label?: T;
        cta1Href?: T;
        cta2Label?: T;
        cta2Href?: T;
        heroImage?: T;
      };
  layout?:
    | T
    | {
        faqBlock?: T | FaqBlockBlockSelect<T>;
        homeSectionAbout?: T | SectionAboutBlockSelect<T>;
        homeSectionLogoCloud?: T | SectionLogoCloudBlockSelect<T>;
        homeSectionProcess?: T | SectionProcessBlockSelect<T>;
        homeSectionProjects?: T | SectionProjectsBlockSelect<T>;
        homeSectionServices?: T | SectionServicesBlockSelect<T>;
        homeSectionStats?: T | SectionStatsBlockSelect<T>;
        homeSectionTestimonials?: T | SectionTestimonialsBlockSelect<T>;
        homeSectionCta?: T | SectionCtaBlockSelect<T>;
        contactSection?: T | ContactSectionBlockSelect<T>;
        homeSectionContact?: T | SectionContactBlockSelect<T>;
        checklistGrid?: T | ChecklistGridBlockSelect<T>;
        pullQuote?: T | PullQuoteBlockSelect<T>;
        portfolioListing?: T | PortfolioListingBlockSelect<T>;
        blogListing?: T | BlogListingBlockSelect<T>;
        latestPosts?: T | LatestPostsBlockSelect<T>;
        latestPortfolios?: T | LatestPortfoliosBlockSelect<T>;
      };
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlockBlock_select".
 */
export interface FaqBlockBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleMaxWidth?: T;
  defaultOpenIndex?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionAboutBlock_select".
 */
export interface SectionAboutBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleMaxWidth?: T;
  description?: T;
  ctaLabel?: T;
  ctaHref?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionLogoCloudBlock_select".
 */
export interface SectionLogoCloudBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleMaxWidth?: T;
  description?: T;
  partners?:
    | T
    | {
        logo?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionProcessBlock_select".
 */
export interface SectionProcessBlockSelect<T extends boolean = true> {
  background?: T;
  eyebrow?: T;
  title?: T;
  titleMaxWidth?: T;
  description?: T;
  highlightIndex?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionProjectsBlock_select".
 */
export interface SectionProjectsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleMaxWidth?: T;
  portfolioLabel?: T;
  portfolioHref?: T;
  projects?:
    | T
    | {
        tag?: T;
        tagVariant?: T;
        accent?: T;
        client?: T;
        year?: T;
        title?: T;
        result?: T;
        motifType?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionServicesBlock_select".
 */
export interface SectionServicesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleMaxWidth?: T;
  description?: T;
  services?:
    | T
    | {
        name?: T;
        variant?: T;
        description?: T;
        iconType?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionStatsBlock_select".
 */
export interface SectionStatsBlockSelect<T extends boolean = true> {
  showDecoration?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionTestimonialsBlock_select".
 */
export interface SectionTestimonialsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleMaxWidth?: T;
  description?: T;
  ratingValue?: T;
  reviewCount?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        avatarVariant?: T;
        surface?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionCtaBlock_select".
 */
export interface SectionCtaBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  title?: T;
  titleMaxWidth?: T;
  description?: T;
  cta1Label?: T;
  cta1Href?: T;
  cta1Variant?: T;
  cta2Label?: T;
  cta2Href?: T;
  cta2Variant?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactSectionBlock_select".
 */
export interface ContactSectionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  sidebarEyebrow?: T;
  successTitle?: T;
  successMessage?: T;
  channels?:
    | T
    | {
        icon?: T;
        label?: T;
        value?: T;
        hint?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionContactBlock_select".
 */
export interface SectionContactBlockSelect<T extends boolean = true> {
  email?: T;
  emailHref?: T;
  phone?: T;
  phoneHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChecklistGridBlock_select".
 */
export interface ChecklistGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleMaxWidth?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock_select".
 */
export interface PullQuoteBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  quote?: T;
  author?: T;
  role?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioListingBlock_select".
 */
export interface PortfolioListingBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleMaxWidth?: T;
  showFilters?: T;
  showViewToggle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogListingBlock_select".
 */
export interface BlogListingBlockSelect<T extends boolean = true> {
  featuredPost?: T;
  eyebrow?: T;
  title?: T;
  titleMaxWidth?: T;
  postsPerPage?: T;
  showSearch?: T;
  showFilters?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPostsBlock_select".
 */
export interface LatestPostsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleMaxWidth?: T;
  buttonLabel?: T;
  buttonHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPortfoliosBlock_select".
 */
export interface LatestPortfoliosBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleMaxWidth?: T;
  buttonLabel?: T;
  buttonHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolios_select".
 */
export interface PortfoliosSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  summary?: T;
  image?: T;
  tag?: T;
  tagVariant?: T;
  accent?: T;
  year?: T;
  result?: T;
  siteUrl?: T;
  nextProjectHref?: T;
  publishedAt?: T;
  sector?: T;
  deliverables?: T;
  duration?: T;
  challengeTitle?: T;
  challengeBody?: T;
  processSteps?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        label?: T;
        accent?: T;
        id?: T;
      };
  quoteText?: T;
  quoteAuthor?: T;
  quoteRole?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  team?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  stack?:
    | T
    | {
        tool?: T;
        id?: T;
      };
  relatedPortfolios?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-tags_select".
 */
export interface PortfolioTagsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  relatedPosts?: T;
  tags?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  featuredImage?: T;
  publishedAt?: T;
  authors?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'portfolios';
          value: number | Portfolio;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}